name: autocentral
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.5
  firebase_messaging: ^14.6.5

  # ğŸ”” Notifications
  flutter_local_notifications: ^17.2.2
  awesome_notifications: ^0.10.1
  timezone: ^0.9.2

  # ğŸŒ RÃ©seau & HTTP
  http: ^1.5.0
  connectivity_plus: ^5.0.1
  rxdart: ^0.27.0

  # ğŸ“± Permissions & Background
  permission_handler: ^11.0.1
  # workmanager: ^0.5.1

  # ğŸ’¾ Stockage & prÃ©fÃ©rences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # ğŸ“ Fichiers & mÃ©dias
  image_picker: ^1.0.4
  # file_picker: ^6.2.1
  file_selector: ^0.9.0
  cached_network_image: ^3.3.0

  # ğŸ“¦ UI & Ã©tat
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.20.0

  # ğŸ•Šï¸ GÃ©nÃ©ration Pigeon
  pigeon: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
