name: autocentral
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ğŸ”¹ Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2

  # ğŸ”” Notifications
  flutter_local_notifications: ^17.2.2
  awesome_notifications: ^0.10.1
  timezone: ^0.9.0

  # ğŸŒ RÃ©seau & HTTP
  http: ^1.5.0
  connectivity_plus: ^5.0.1
  rxdart: ^0.28.0

  # ğŸ“± Permissions & Background
  permission_handler: ^12.0.1
  # workmanager: ^0.5.1

  # ğŸ’¾ Stockage & prÃ©fÃ©rences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  open_file: ^3.5.10   # <-- Ã  ajouter
  pdfx: ^2.9.2

  # ğŸ“ Fichiers & mÃ©dias
  image_picker: ^1.0.4
  # file_picker: ^6.2.1
  file_selector: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_image_compress: ^2.4.0
  image: ^4.2.0

  # ğŸ“¦ UI & Ã©tat
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  intl: ^0.20.0

  # ğŸ•Šï¸ GÃ©nÃ©ration Pigeon
  pigeon: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
